### ISSUE TITLE
[ BUG ] Sending credentials in the request payload causes issues with certain HTTP libraries

### ISSUE THREAD

**Issue by joseywoermann** [ScarletAI/Scarlet#5] opened 2021-12-16 21:16 UTC
**Describe the bug**
As per [specification](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET), `GET` should NOT include a (JSON) payload.
This can cause errors in HTTP libraries when accessing endpoints like `/users/:id` which require a payload to be sent in a `GET` request.

**To Reproduce**
As an example, run the following:
```js
import fetch from "node-fetch";

const res = await fetch("https://api.scarletai.xyz/users/1234567890", {
    body: JSON.stringify({
        username: "your_username",
        password: "your_password",
        token: "y.ourtoken_here",
    })
});
const data = await res.json();
console.log(data);
```

**Observation**
`node-fetch` refuses to send the request:
```
G:\diverses\node>node index.js
file:///G:/diverses/node/node_modules/node-fetch/src/request.js:65
                        throw new TypeError('Request with GET/HEAD method cannot have body');
                              ^

TypeError: Request with GET/HEAD method cannot have body
    at new Request (file:///G:/diverses/node/node_modules/node-fetch/src/request.js:65:10)
    at file:///G:/diverses/node/node_modules/node-fetch/src/index.js:38:19
    at new Promise (<anonymous>)
    at fetch (file:///G:/diverses/node/node_modules/node-fetch/src/index.js:36:9)
    at main (file:///G:/diverses/node/index.js:4:19)
    at file:///G:/diverses/node/index.js:14:1
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

**Additional context**
I don't know which HTTP libraries tolerate payloads in GET request and which don't, but I assume that most libraries don't allow it.

**Comment by KazutoKashima** [comment] 2021-12-17 00:01
🤔The server actually requires the payload as it gives the users their full account credentials.
See the following snippet from `/users/controllers/users.controller.js`
```js
exports.getById = async (req, res) => {
  // async function checkUser(req) {
  // ... fetch user from a db etc.
  if (!req.body) return syslog.info(`Client tried to gain access to the API, without a body request`), res.status(401).send('No request body detected');

  const match = await bcrypt.compare(req.body.password, await user[0].password);

  if (match) {
    await UserModel.find({uuid: req.body.id, token: req.body.token}).then(async((result) => {
      syslog.log(`Client retrieved UserID from API`);
      return res.send({status: 'ok', message: `${result.uuid}\n${result.username}\n${result.password}\n${result.token}\n${result.permissionLevel}`});
    }));
  } else {
    return res.status(401).send({message: 'Authentication Failed'});
  }
  checkUser(req);
};
```
So as an internal security measure, Scarlet is not allowed to pass along her user's data without first having the correct data to their account

**Comment by joseywoermann** [comment] 2021-12-17 05:45
> 🤔The server actually requires the payload as it gives the users their full account credentials.
> See the following snippet from `/users/controllers/users.controller.js`
> ```js
> exports.getById = async (req, res) => {
>   // async function checkUser(req) {
>   // ... fetch user from a db etc.
>   if (!req.body) return syslog.info(`Client tried to gain access to the API, without a body request`), res.status(401).send('No request body detected');
> 
>   const match = await bcrypt.compare(req.body.password, await user[0].password);
> 
>   if (match) {
>     await UserModel.find({uuid: req.body.id, token: req.body.token}).then(async((result) => {
>       syslog.log(`Client retrieved UserID from API`);
>       return res.send({status: 'ok', message: `${result.uuid}\n${result.username}\n${result.password}\n${result.token}\n${result.permissionLevel}`});
>     }));
>   } else {
>     return res.status(401).send({message: 'Authentication Failed'});
>   }
>   checkUser(req);
> };
> ```
> So as an internal security measure, Scarlet is not allowed to pass along her user's data without first having the correct data to their account

This all makes sense, but passing them as the _body_ is the problem. Because the official specification for HTTP GET says that GET requests shouldn't contain a body, some / a lot of the HTTP libaries don't support sending a payload with GET request.

A possible solution would be to send the credentials through the headers.

**Comment by KazutoKashima** [comment] 2021-12-17 06:24
🤔 I'll take a look into converting it into the headers instead of the body.
Hopefully it shouldn't be that hard

**Comment by KazutoKashima** [comment] 2022-01-02 02:10
I've started looking into this, Assuming that we are going token heavy on the API, the mock up of the headers would be something like this, I assume?

```js
// creds is a JSON defined earlier on or in a POST form

const options = {
    hostname: 'api.scarletai.xyz',
    port: 443,
    path: '/scarlet/talk',
    method: 'POST',
    headers: {
        'Content-Type': 'application/json; charset=utf-8',
        'Authorization': 'Bearer ' + creds.token
    },
    body: {
        "message": message,
        "username": creds.username,
        "password": creds.password,
        "channel": creds.channel,
        "server": creds.server
    }
};
```
But the issue is sending the other details🤔
I assume it would be simpler to use queries in the URL instead. Like so:
```py
# This isn't an actual link
https://api.scarletai.xyz/users?id=1233456&token=[the token]&username=sometestAccount
```

**Comment by joseywoermann** [comment] 2022-01-02 10:36
The header mockup looks good to me.

Passing the token as a URL parameter wouldn't work that well because the token can contain chars like `/`, `$` & `.`. That means that the user would have to encode ot on their end and the server has to decode it, which would make it more complicated than using headers.

**Comment by KazutoKashima** [comment] 2022-01-02 23:35
Good point on the params, I'll put together an official header system to the rest of the API instead of just to the test CDN system, when I can.

Feel free to nit-pick the `ScarletCDN` branch for anything that should be changed

**Comment by KazutoKashima** [comment] 2022-01-05 03:02
@joseywoermann How does this look?
```js
// parse application/json
app.use(bp.json());
app.use(function(req, res, next) {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Credentials', 'true');
  res.header('Access-Control-Allow-Methods', 'GET,HEAD,PUT,PATCH,POST,DELETE');
  res.header('Access-Control-Expose-Headers', 'Content-Length');
  res.header('Access-Control-Allow-Headers',
      'Accept, Authorization, Content-Type, X-Requested-With, Range');
  res.header('Content-Type', 'application/json');
  res.header('Access-Control-Max-Age', '1728000');
  res.header('Authorization', `Bearer ${req.headers.authorization}, User ${req.headers.id}, Password ${req.headers.password}`);
  if (req.method === 'OPTIONS') {
    return res.status(200).send();
  } else {
    return next();
  }
});
```

**Comment by KazutoKashima** [comment] 2022-01-06 03:11
> **We do not need to use pre-defined headers, we can create our own.**

I know, but those headers were implemented first and I'd rather not remove/change them to avoid breaking anything.

> assing all credentials through the Authorization header is definitely possible, but I think it would be more user-friendly if there were seperate headers for username, password and token. (for example `req.headers.username`, `req.headers.password` & `req.headers.token`)
I'll consider this, it maybe easier to allow this if they aren't using a web-interface, but instead directly communicating with the API
Theoretically doing: `HEADER: Scarlet-Token, Scarlet-ID, Scarlet-Pass` should be user-friendly and easy to manage

**Comment by KazutoKashima** [comment] 2022-04-01 04:24
@joseywoermann 
I got this all cleared up and implemented into GET/DELETE of the user paths with Basic Auth, since it was easier to use a common method over a new proprietary one
See: #18 (dev build, also running on the server since it's relatively stable)

**Comment by KazutoKashima** [comment] 2022-05-08 10:43
Forgot to close this apparently lmaooo

**Closed by KazutoKashima** 2022-05-08 10:43 UTC
Labels: bug
